### ISSUE TITLE
xmlns:default added, how to remove?

### ISSUE THREAD

**Issue by josh-patchworks** [veewee/xml#51]
|    Q        |   A
|------------ | -----
| Version     | 2.6.0

### Support Question

Firstly, awesome work on this package! I am testing this against some xml that is returned from a 3rd party api call. I am using `xml_decode()` then `xml_encode()` to see how to xml is transformed:

Before transformation:
```
...
<soapenv:Envelope
        xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
...
```

After transformation:
```
...
<soapenv:Envelope
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
        xmlns:default="urn:messages_2022_1.platform.webservices.netsuite.com">
...
```

There is an extra attribute added. In theory after decoding and encoding I should end up with the same xml string. Is there a certain configuration detail I am missing?

**Comment by veewee** [comment]
In theory it should indeed match. Depending on what is being done with the document, it is however possible that some namespace declarations are placed on parent elements as an internal optimization of PHPs DOM extension.
Technically, the output will be the correct XML, just not matching the input XML in this case.

Can you share a bit more of what you are doing?
 

Some more info:
https://github.com/veewee/xml/blob/main/docs/encoding.md#element_decode

If you're dealing with SOAP, you might take a look at this package
https://github.com/php-soap/xml

It are helper functions for reading/writing in soap XML.

**Comment by josh-patchworks** [comment]
This is for a data manipulation system. So we need to be able to decode xml into an array, perform operations on it (usually filtering elements out), then reconstruct the xml.

For example, take an XML response from an e-commerce api which contains all of the orders from the past month. We then convert the xml to an array to filter out the paid orders. From there we change the array back into xml.

**Comment by veewee** [comment]
These kind of manipulations might be easier with Dom and xpath.
However, since the result of the encoded XML should be valid and acceptable XML, I don't think this is an issue. (At least one I can do anything about from this library)
