### ISSUE TITLE
forFile fails if file does not exist

### ISSUE THREAD

**Issue by mvenghaus** [veewee/xml#70]
### Bug Report

When using forFile .. is_writeable fails if file not exists. 

#### Summary

I always have to create an empty file before i can use this function, otherwise i get a runtime exception.

#### How to reproduce
```php
Writer::forFile('test.xml')
    ->write(document('1.0', 'UTF-8'));
```

#### Current behaviour

PHP Fatal error:  Uncaught Webmozart\Assert\InvalidArgumentException: The path "test.xml" is not writable

#### Expected behaviour

Create the file because the directory is writeable.

**Comment by veewee** [comment]
Thanks for reporting. That sure sounds like a good improvement!

**Comment by veewee** [comment]
Fixed in https://github.com/veewee/xml/pull/71
