### ISSUE TITLE
Loading UTF-16 XML

### ISSUE THREAD

**Issue by bendavies** [veewee/xml#75]
Hi there,

it is possible to load/read xml with an encoding of UTF-16?

for  example:

```xml
<?xml version="1.0" encoding="utf-16" standalone="yes"?>
<Response>
  <IsSuccessful>false</IsSuccessful>
  <Data></Data>
  <Errors>
    <Error>InsuredEmail required.</Error>
    <Error>AgentEmail required.</Error>
    <Error>InsuredEmail is not a valid e-mail address.</Error>
    <Error>AgentEmail is not a valid e-mail address.</Error>
  </Errors>
</Response>
```

loading with `xml_decode` or `Document` will result in
`Could not load the DOM Document
[FATAL] : Document labelled UTF-16 but has UTF-8 content
 (81) on line 1,38`

thanks!

**Comment by veewee** [comment]
Hello there,

I haven't really experimented with UTF16 XML yet tbh.
But the general approach would be to:

```php
use VeeWee\Xml\Dom\Document;
use function VeeWee\Xml\Dom\Configurator\loader;
use function VeeWee\Xml\Dom\Loader\xml_string_loader;

$doc = Document::configure(
    utf16(),
    loader(xml_string_loader($utf16String))
);
```

This package currently does not ship with a utf16 configurator, but you can take a look at the UTF8 one to base it upon:

```php
/**
 * @return Closure(DOMDocument): DOMDocument
 */
function utf16(): Closure
{
    return static function (DOMDocument $document): DOMDocument {
        $document->encoding = 'UTF-16';

        return $document;
    };
}
```

If you want to use `xml_decode`, you probably have to build the document first and use `element_decode` instead. You can pass in configurators, but you'll need to set the encoding before loading the xml string.

**Comment by bendavies** [comment]
Hi, thanks for the reply.

I actually tried exactly, that, but still got the error that i posted in the OP!

**Comment by bendavies** [comment]
ok, looked at this again.
this does work if i run the string though
```php
\Psl\Str\convert_encoding($xml, \Psl\Str\Encoding::UTF_8, \Psl\Str\Encoding::UTF_16),
```

I'll check, but i think this is an issue with the actual soap webservice returning utf-8 content  instead of utf-16, or it's being converted automatically somewhere my end...

Thanks!
