### ISSUE TITLE
Fatal error: Cannot redeclare VeeWee\Xml\Dom\Assert\assert_attribute()

### ISSUE THREAD

**Issue by sprankhub** [veewee/xml#76]
|    Q        |   A
|------------ | -----
| Version     | 3.1.0

### Support Question

I am using this library inside a Magento 2 project. When running a CLI command, I get an error related to this library:

    $ bin/magento yireo_extensionchecker:scan --module Vendor_Module

    Fatal error: Cannot redeclare VeeWee\Xml\Dom\Assert\assert_attribute() (previously declared in /var/www/html/vendor/veewee/xml/src/Xml/Dom/Assert/assert_attribute.php:15) in /var/www/html/vendor/veewee/xml/src/Xml/Dom/Assert/assert_attribute.php on line 17

I tried to debug the issue, but I cannot wrap my head around it. The issue pretty much says that in line 17 of `/var/www/html/vendor/veewee/xml/src/Xml/Dom/Assert/assert_attribute.php`, the method `VeeWee\Xml\Dom\Assert\assert_attribute()` is declared. However, line 17 doesn't declare a method at all:

https://github.com/veewee/xml/blob/47504aec3a1a8146ff7e870acce07b561e3c2947/src/Xml/Dom/Assert/assert_attribute.php#L17

I know it is a very poor issue, because it is not possible to reproduce this. I still wanted to ask you, whether you have any idea by chance? Have you seen this before?

Thanks!

**Comment by veewee** [comment]
This package comes shipped with an autoloader that checks if the function exists before loading the file to avoid these kind of errors.

This means that the specific tool you are using is using a custom autoloader either explicit or implicit by using something like `class_exists()` or friends.

Sadly there is no central function autoloader logic in php yet.

**Comment by sprankhub** [comment]
Thanks a lot for your help! I've further looked into this and found out that the issue is caused by a call to `class_exists('VeeWee\Xml\Dom\Assert\assert_attribute')`. The issue is described in more detail here: https://github.com/yireo/Yireo_ExtensionChecker/issues/53
